title: Workbook
description: Моя база знаний по технологиям, языкам, фреймворкам.
theme: just-the-docs

url: https://fullmetalprogrammist.github.io/workbook

just_the_docs:
  heading_anchors: true
  toc: true